name: flutter-test

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: conet_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.38.3

      - name: Create .env file
        run: echo "API_URL=http://10.0.2.2:3000" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test
